name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: autoUptodate
          token: ${{ secrets.UPTODATE }}
      - name: Fork Sync With Upstream
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v2.0
        with:          
          upstream_repository: TheAlgorithms/Python
          upstream_branch: master
          target_branch: autoUptodate
          git_pull_args: --ff-only
      - name: Check for new commits
        if: steps.sync.outputs.has-new-commits
        run: echo "There were new commits."
